import dspy
import argparse
import os
import sys

# Define Signature
class VLMTask(dspy.Signature):
    """Answer questions about an image."""
    
    image: dspy.Image = dspy.InputField(desc="Path to the image")
    question: str = dspy.InputField(desc="Question about the image")
    code: str = dspy.OutputField(desc="The code generated by the VLM enclosed in ```python and ```")
    rationale: str = dspy.OutputField(desc="The rationale for the code generation")

# Define Module
class VLMModule(dspy.Module):
    def __init__(self):
        super().__init__()
        self.predictor = dspy.Predict(VLMTask)

    def forward(self, image, question):
        return self.predictor(image=image, question=question)

def main():
    parser = argparse.ArgumentParser(description="VLM Code Generator using dspy")
    parser.add_argument("image_path", help="Path to the input image")
    parser.add_argument("question", help="Question to ask about the image")
    parser.add_argument("output_path", help="Path to save the generated code")
    parser.add_argument("--model", default=os.environ.get("OPENAI_MODEL", "Qwen/Qwen3-VL-8B-Thinking"), help="Model name (default: env OPENAI_MODEL or Qwen/Qwen3-VL-8B-Thinking)")
    parser.add_argument("--api_base", default=os.environ.get("OPENAI_API_BASE", "http://localhost:8000/v1"), help="API base URL (default: env OPENAI_API_BASE or http://localhost:8000/v1)")
    parser.add_argument("--api_key", default=os.environ.get("OPENAI_API_KEY", "EMPTY"), help="API key (default: env OPENAI_API_KEY or EMPTY)")

    args = parser.parse_args()

    # Configure dspy LM
    lm = dspy.LM(
        model=args.model,
        api_base=args.api_base,
        api_key=args.api_key,
        model_type='chat'
    )
    dspy.configure(lm=lm)

    # Read system prompt
    try:
        with open("src/code.md", "r") as f:
            system_prompt = f.read().strip()
            # Update the docstring of the signature with the system prompt
            VLMTask.__doc__ = system_prompt
    except FileNotFoundError:
        print("Error: src/code.md not found.", file=sys.stderr)
        sys.exit(1)

    # Execute
    try:
        # Check if image exists
        if not os.path.exists(args.image_path):
             print(f"Error: Image file '{args.image_path}' not found.", file=sys.stderr)
             sys.exit(1)

        # Create dspy Image object
        img = dspy.Image.from_file(args.image_path)

        module = VLMModule()
        response = module(image=img, question=args.question)
        
        print("Rationale:", response.rationale)
        print("Code:", response.code)

        # Save code to file
        code_content = response.code
        # Simple cleanup of markdown code blocks if present
        if code_content.startswith("```python"):
            code_content = code_content[9:]
        elif code_content.startswith("```"):
            code_content = code_content[3:]
        if code_content.endswith("```"):
            code_content = code_content[:-3]
        
        with open(args.output_path, "w") as f:
            f.write(code_content.strip())
        print(f"Generated code saved to {args.output_path}")

    except Exception as e:
        print(f"Error during VLM execution: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
